export const SET_WALLET_CONNECTION_STATUS = 'SET_WALLET_CONNECTION_STATUS';

export const SET_NET_CONNECTION_STATUS = 'SET_NET_CONNECTION_STATUS';

export const SET_COINBASE_ADDRESS = 'SET_COINBASE_ADDRESS';